---
- name: Configure Web Server
  hosts: web
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Enable Nginx in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/nginx.repo

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create shared folder for NFS
      file:
        path: /srv/shared
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0775'
